version: "3"
services:
  # exercise3:
  #   build: .
  #   ports:
  #     - "9003:9003"
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  # mongodb:
  #   image: mongo
  #   volumes:
  #     - ./data/db:/data/db
  #   ports:
  #     - 27017:27017
  # mongodb2:
  #   image: mongo  
  #   volumes:
  #     - ./data/db2:/data/db2
  #   ports:
  #     - 27018:27017
